name: Node CI

on:
  push:
    branches: [CI/CD-pipeline]
  pull_request:
    branches: [dev]


jobs:
  test_pull_request:
    runs-on: ubuntu-
    steps:
      - uses: actions/checkout@v2 #get the source code into the curret working directory
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build

